# Generated by Django 4.1.6 on 2023-05-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAsset', models.IntegerField()),
                ('audio', models.CharField(default='img_video/giobien.mp3', max_length=100)),
                ('video', models.CharField(default='/static/img_video/video.mp4', max_length=100)),
            ],
        ),
    ]
