# Generated by Django 4.1.6 on 2023-05-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanApp', '0004_user_gender_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
