# Generated by Django 4.1.6 on 2023-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanApp', '0005_alter_user_createat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='idAsset',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='idPost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='idUser',
            field=models.CharField(max_length=100),
        ),
    ]
