# Generated by Django 4.1.6 on 2023-05-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanApp', '0006_alter_asset_idasset_alter_blog_idpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.CharField(default='https://tranhoangkhang1212.github.io/travelix/assets/images/xintro_1.jpg.pagespeed.ic.vc2WNRX2pm.webp', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/2048px-User-avatar.svg.png', max_length=500),
        ),
    ]
