# Generated by Django 4.1.6 on 2023-05-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanApp', '0007_alter_blog_thumbnail_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='destination',
            field=models.CharField(default='world', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
