# Generated by Django 4.1.6 on 2023-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanApp', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='idAuthor',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
