# Generated by Django 4.1.6 on 2023-05-24 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OceanApp', '0011_blog_idauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComent', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OceanApp.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OceanApp.blog')),
            ],
        ),
    ]
