# Generated by Django 4.1.6 on 2023-05-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OceanApp', '0012_alter_blog_content_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='idComent',
        ),
    ]
