# Generated by Django 4.1.6 on 2023-05-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanApp', '0014_comment_author_comment_idcoment_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='idComent',
        ),
        migrations.AddField(
            model_name='comment',
            name='idComment',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
